status = warn
name = ConsoleConfig

# ========================
# Appenders
# ========================

appender.stdout.type = Console
appender.stdout.name = STDOUT
appender.stdout.target = SYSTEM_OUT
appender.stdout.filter.threshold.type = ThresholdFilter
appender.stdout.filter.threshold.level = warn
appender.stdout.filter.threshold.onMatch = deny
appender.stdout.filter.threshold.onMismatch = accept
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.disableAnsi = false
appender.stdout.layout.pattern = %style{%d{yyyy-MM-dd HH:mm:ss.SSS}}{magenta} %highlight{%-5level} [%t] %style{%c}{cyan} - %msg%n

appender.stderr.type = Console
appender.stderr.name = STDERR
appender.stderr.target = SYSTEM_ERR
appender.stderr.filter.threshold.type = ThresholdFilter
appender.stderr.filter.threshold.level = warn
appender.stderr.layout.type = PatternLayout
appender.stderr.layout.disableAnsi = false
appender.stderr.layout.pattern = %style{%d{yyyy-MM-dd HH:mm:ss.SSS}}{magenta} %highlight{%-5level} [%t] %style{%c}{cyan} - %msg%n

# ========================
# Root Logger
# ========================

rootLogger.level = info
rootLogger.appenderRefs = stdout, stderr
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.stderr.ref = STDERR
